spring.datasource.url=jdbc:mysql://10.0.0.50:3306/employee_management_prod
spring.datasource.username=admin_production
spring.datasource.password=VeryStrongPassword!@#

logging.level.com.example.employeemanagement=ERROR
spring.jpa.show-sql=false