spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Cache configuration
spring.cache.cache-names=employeeCount
spring.cache.caffeine.spec=expireAfterWrite=60s